pure_pursuit:
  ros__parameters:
    trajectory_csv: "/sim_ws/src/f1tenth_gym_ros/racelines/levine.csv"
    pp_steer_L_fast: 2.5
    pp_steer_L_slow: 1.8
    kp_fast: 0.35
    kp_slow: 0.5
    L_threshold_speed: 4.0
    odom_topic: "ego_racecar/odom"
    pure_pursuit_velocity_topic: "pure_pursuit_velocity"
    drive_topic: "drive"
    use_obs_avoid_topic: "use_obs_avoid"
    